# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

# 分析主程序
a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('src', 'src'),  # 包含源代码目录
    ],
    hiddenimports=[
        'tkinter',
        'tkinter.ttk',
        'ttkthemes',
        'PIL',
        'PIL.Image',
        'PIL.ImageTk',
        'PIL.ImageFont',
        'PIL.ImageDraw',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        # 排除不需要的标准库模块
        'pytest',
        'setuptools',
        'pip',
        'wheel',
        'distutils',
        'email',
        'http',
        'urllib3',
        'xml',
        'unittest',
        'test',
        'pydoc',
        'doctest',
        'difflib',
        'inspect',
        'multiprocessing',
        'concurrent',
        'asyncio',
        'sqlite3',
        'ssl',
        'socket',
        'select',
        'ctypes.wintypes',
        # 排除其他不需要的模块
        'numpy',
        'scipy',
        'matplotlib',
        'pandas',
        'requests',
        'urllib',
        'json',
        'csv',
        'logging',
        'argparse',
        'optparse',
        'getopt',
        'cmd',
        'readline',
        'rlcompleter',
        'pdb',
        'profile',
        'pstats',
        'timeit',
        'trace',
        'calendar',
        'datetime',
        'time',
        'locale',
        'gettext',
        'codecs',
        'encodings',
        'unicodedata',
        'stringprep',
        'fpectl',
        'gc',
        'weakref',
        'copy',
        'pickle',
        'copyreg',
        'shelve',
        'marshal',
        'anydbm',
        'whichdb',
        'dbm',
        'gdbm',
        'dbhash',
        'bsddb',
        'dumbdbm',
        'zlib',
        'gzip',
        'bz2',
        'zipfile',
        'tarfile',
        'csv',
        'ConfigParser',
        'robotparser',
        'netrc',
        'xdrlib',
        'plistlib',
        'pprint',
        'repr',
        'numbers',
        'math',
        'cmath',
        'decimal',
        'fractions',
        'random',
        'itertools',
        'functools',
        'operator',
        'string',
        're',
        'struct',
        'difflib',
        'textwrap',
        'codecs',
        'unicodedata',
        'stringprep',
        'readline',
        'rlcompleter',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

# 排除不需要的二进制文件
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

# 创建可执行文件
exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='album-scanner',
    debug=False,
    bootloader_ignore_signals=False,
    strip=True,  # 去除调试信息
    upx=True,    # 使用UPX压缩（如果可用）
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,  # Windows下不显示控制台窗口
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)