name: Build and Package

on:
  push:
    branches:
      - main
  release:
    types: [created]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 设置 Python 环境
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # 安装依赖
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pyinstaller

      # 安装 UPX (仅 Windows)
      - name: Install UPX (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          curl -L -o upx.zip https://github.com/upx/upx/releases/download/v4.2.1/upx-4.2.1-win64.zip
          7z x upx.zip
          move upx-4.2.1-win64\upx.exe upx.exe

      # 打包为可执行文件
      - name: Build executable (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          pyinstaller --onefile --name comic-reader main.py

      - name: Build executable (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          pyinstaller --onefile --optimize=2 --strip --upx-dir=. --name comic-reader main.py

      # 上传构建工件
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: comic-reader-${{ matrix.os }}
          path: dist/comic-reader${{ matrix.os == 'windows-latest' && '.exe' || '' }}
  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    permissions:
      contents: write

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 下载构建工件
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: comic-reader-ubuntu-latest
          path: ./dist/ubuntu
      
      - name: Download Windows artifact
        uses: actions/download-artifact@v4
        with:
          name: comic-reader-windows-latest
          path: ./dist/windows

      # 重命名文件以便更好地识别
      - name: Rename artifacts
        run: |
          mv ./dist/ubuntu/comic-reader ./dist/ubuntu/comic-reader-linux
          mv ./dist/windows/comic-reader.exe ./dist/windows/comic-reader-windows.exe
          chmod +x ./dist/ubuntu/comic-reader-linux

      # 发布 Release 并上传文件
      - name: Upload Release Assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # 检查 release 是否存在
          if ! gh release view ${{ github.event.release.tag_name }} --repo ${{ github.repository }} > /dev/null 2>&1; then
            echo "Release ${{ github.event.release.tag_name }} not found"
            exit 1
          fi
          
          # 上传文件到 release
          gh release upload ${{ github.event.release.tag_name }} \
            ./dist/ubuntu/comic-reader-linux \
            ./dist/windows/comic-reader-windows.exe \
            --repo ${{ github.repository }} \
            --clobber
