name: Build and Package

on:
  push:
    branches:
      - main
  release:
    types: [created]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 设置 Python 环境
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # 安装依赖
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pyinstaller

      # 安装UPX压缩工具 (Windows)
      - name: Install UPX (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          choco install upx -y

      # 安装UPX压缩工具 (Linux)
      - name: Install UPX (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y upx

      # 打包为可执行文件 (使用优化的spec文件)
      - name: Build executable
        run: |
          pyinstaller --clean --noconfirm album-scanner.spec

      # 进一步压缩可执行文件 (Windows)
      - name: Compress executable (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          upx --best --lzma dist/album-scanner.exe
        continue-on-error: true

      # 进一步压缩可执行文件 (Linux)
      - name: Compress executable (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          upx --best --lzma dist/album-scanner
        continue-on-error: true

      # 上传构建工件
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: album-scanner-${{ matrix.os }}
          path: dist/album-scanner${{ matrix.os == 'windows-latest' && '.exe' || '' }}
  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    permissions:
      contents: write

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 下载构建工件
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: album-scanner-ubuntu-latest
          path: ./dist/ubuntu
      
      - name: Download Windows artifact
        uses: actions/download-artifact@v4
        with:
          name: album-scanner-windows-latest
          path: ./dist/windows

      # 重命名文件以便更好地识别
      - name: Rename artifacts
        run: |
          mv ./dist/ubuntu/album-scanner ./dist/ubuntu/album-scanner-linux
          mv ./dist/windows/album-scanner.exe ./dist/windows/album-scanner-windows.exe
          chmod +x ./dist/ubuntu/album-scanner-linux

      # 发布 Release 并上传文件
      - name: Upload Release Assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # 检查 release 是否存在
          if ! gh release view ${{ github.event.release.tag_name }} --repo ${{ github.repository }} > /dev/null 2>&1; then
            echo "Release ${{ github.event.release.tag_name }} not found"
            exit 1
          fi
          
          # 上传文件到 release
          gh release upload ${{ github.event.release.tag_name }} \
            ./dist/ubuntu/album-scanner-linux \
            ./dist/windows/album-scanner-windows.exe \
            --repo ${{ github.repository }} \
            --clobber
